layers.schema.json: Add missing schema
This resolves the jsonschema error:
  error: The JSON document is not a valid JSON Schema

Reviewed-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Rob Woolley <rob.woolley@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>